auth.db.url="jdbc:postgresql://localhost:5432/auth_db"
auth.db.username="postgres"
auth.db.password="Akul@789"

erp.db.url="jdbc:postgresql://localhost:5432/erp_db"
erp.db.username="postgres"
erp.db.password="Akul@789"
